### PR TITLE
Organize the SDK / simplify the SDK / add Docker support / renv eveything

### PR DESCRIPTION
**Pull request by cleemansen**
This is IMHO a general improvement of the SDK.

1. structurize the project
2. add docker support
3. add renv for R packaging

Still WIP and just a base for discussion.

### CODE REVIEW

**Comment by andreakoelzsch** [comment]
Hi both, thanks for the overview. Looks good. Maybe one should give an option (or just write a comment howto) for the user to disconnect the renv, as that can be rather disturbing if one is not using it cusomarily. I can look in details and code tomorrow.

**Comment by cleemansen** [comment]
Yes, I agree that `renv` should not scare people to build apps. As I'm not using RStudio for developing I don't know if it is possible to irgnore `renv` with this template.

Can somebody try to build a new app in RStudio with this new template?

**Comment by cleemansen** [comment]
If this PR gets accepted we have to do:

- [ ] update Template Shiny
- [ ] update Template Shiny Dashboard
- [ ] accept the PR of the user manual

**Comment by cleemansen** [comment]
I have an issue consuming the sample input `input1_pigeons.rds`. I'm not sure if

- a) the changed SDK in general introduced this error. This is unlikly b/c everything works w/ input `input2_geese.rds`
- b) the changed R runtime
- c) the upgraded move version
- d) something else.

Error details:

```
[DEBUG] Reading RDS from file './data/raw/input1_pigeons.rds'
[1] "ERROR:  Error in validityMethod(as(object, superClass)): The data in the MoveStack object are not grouped per individual\n"
```

@annescharf : can you have a look into this? Feel free to contact me about more details..

**Comment by annescharf** [comment]
> I have an issue consuming the sample input `input1_pigeons.rds`. I'm not sure if
> 
>     * a) the changed SDK in general introduced this error. This is unlikly b/c everything works w/ input `input2_geese.rds`
> 
>     * b) the changed R runtime
> 
>     * c) the upgraded move version
> 
>     * d) something else.
> 
> 
> Error details:
> 
> ```
> [DEBUG] Reading RDS from file './data/raw/input1_pigeons.rds'
> [1] "ERROR:  Error in validityMethod(as(object, superClass)): The data in the MoveStack object are not grouped per individual\n"
> ```
> 
> @annescharf : can you have a look into this? Feel free to contact me about more details..

Hi Clemens, dieser Fehler kommt nur weil die Beispiel Funktion sehr einfach ist und nicht mit der situatuon umgeht wenn alle Tiere nach der auswahl 0 Positionen haben. Also kein Problem vom SDK

**Pull request merged**
